/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./site/**/*.html'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#544524',
        'on-primary-container': '#463819',
        'on-tertiary-fixed-variant': '#484742',
        'primary': '#dac49a',
        'error-container': '#93000a',
        'surface-tint': '#dac49a',
        'surface-container-highest': '#353534',
        'on-tertiary-container': '#3b3a35',
        'secondary-container': '#474742',
        'on-primary': '#3c2f10',
        'outline': '#989083',
        'tertiary-fixed-dim': '#c9c6bf',
        'on-primary-fixed': '#251a01',
        'inverse-surface': '#e5e2e1',
        'on-secondary-fixed': '#1c1c18',
        'secondary-fixed': '#e5e2db',
        'tertiary': '#c9c6bf',
        'primary-container': '#b6a27a',
        'secondary': '#c9c6c0',
        'on-error-container': '#ffdad6',
        'surface-dim': '#131313',
        'surface-container-high': '#2a2a2a',
        'on-error': '#690005',
        'surface-container-low': '#1c1b1b',
        'on-surface': '#e5e2e1',
        'on-secondary-fixed-variant': '#474742',
        'tertiary-fixed': '#e5e2db',
        'surface-variant': '#353534',
        'on-tertiary': '#31312c',
        'background': '#131313',
        'on-surface-variant': '#cec5b8',
        'on-tertiary-fixed': '#1c1c18',
        'on-background': '#e5e2e1',
        'error': '#ffb4ab',
        'on-secondary': '#31312c',
        'outline-variant': '#4c463c',
        'tertiary-container': '#a6a49e',
        'primary-fixed': '#f7e0b4',
        'inverse-primary': '#6d5c3a',
        'secondary-fixed-dim': '#c9c6c0',
        'surface-container': '#201f1f',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'inverse-on-surface': '#313030',
        'on-secondary-container': '#b7b5af',
        'surface': '#131313',
        'primary-fixed-dim': '#dac49a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1440px',
        'gutter': '32px',
        'base': '8px',
        'section-gap': '128px',
        'margin-desktop': '64px',
        'margin-mobile': '24px',
      },
      fontFamily: {
        'display-lg': ['Bodoni Moda', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-md': ['Bodoni Moda', 'serif'],
        'headline-lg-mobile': ['Bodoni Moda', 'serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-xs': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Bodoni Moda', 'serif'],
        'headline-lg': ['Bodoni Moda', 'serif'],
      },
      fontSize: {
        'display-lg': ['80px', { lineHeight: '90px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-md': ['56px', { lineHeight: '64px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-xs': ['10px', { lineHeight: '14px', letterSpacing: '0.15em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '48px', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
